### ISSUE TITLE
Kali Linux "sh: 1: color: Permission denied"

### ISSUE THREAD

**Issue by Ax1rc** [termcolor/termcolor#77] opened 2024-04-14 18:07 UTC
The termcolor module works on Windows but when I try to run it on Kali Linux, it says "sh: 1: color: Permission denied" on my terminal. However, my program still works. Do you know what the cause of the message is? Thank you!

**Comment by hugovk** [comment] 2024-04-14 19:16
Please can you give more details? For example:

### What did you do?

### What did you expect to happen?

### What actually happened?

### What versions are you using?

* OS: 
* Python: 
* termcolor: 

Please include **code** that reproduces the issue.

The [best reproductions](https://stackoverflow.com/help/minimal-reproducible-example) are [self-contained scripts](https://ericlippert.com/2014/03/05/how-to-debug-small-programs/)
with minimal dependencies.

**Comment by L01i74** [comment] 2024-04-17 11:02
**Why It Happened:** This issue usually pops up because Windows and Linux treat file permissions a bit differently. In Linux, newly created files typically aren't given execute permissions by default. So, if you try running a script and bump into a permission error like "sh: 1: color: Permission denied," it means you're trying to execute a script called "color" which lacks the necessary permissions. Here, "sh" refers to the shell or command interpreter that Linux uses by default for scripts, and "1" indicates that the problem is cropping up right at the first line.

**Solution:** To fix this, simply run the command "chmod +x color". This command adjusts the file's settings so you can execute it. If your script is named something other than "color," just swap out "color" for whatever your script's name is.

Also, make sure to insert this line at the top of your script: "#!/bin/python" — it's the path to the Python interpreter on your system and it tells the shell exactly how to run your script.

If you still run into some issues, provide more details, please.

**Comment by Ax1rc** [comment] 2024-04-20 22:45
Thank you for letting me know! I tried running the command that you provided and I also added "#!bin/python" at the top of my script. However, I still see the error (see the first image below for the error and the second image for a section of my code). I am using Python 3.11.6, the latest version. The operating system of my PC is Windows 11 but I installed the Kali Linux terminal as a partition on my disk, which is what I am using to run my program. As I mentioned before, my script works. I am just wondering if there is a way to make it so the "sh: 1: color: Permission denied" message does not show. Also, I am coding a Discord bot in case you are wondering.
![image](https://github.com/termcolor/termcolor/assets/104878465/6c75e045-93c8-4fed-8a99-7e9dcde1cdbd)
![image](https://github.com/termcolor/termcolor/assets/104878465/cc9e86de-92fc-471d-861e-23ea6fb6e1db)

**Comment by L01i74** [comment] 2024-04-21 01:00
**Issue Explained:** The problem stems from the 22nd line in your script: os.system('color'). The os library, part of Python's standard offerings, facilitates lower-level operating system interactions. In your case, you're using the python3 command typical on Kali Linux, which is based on CPython. This command utilizes the system() function from C's stdlib.h, creating a sub-process that executes a shell command specified as a string.

On Unix-like systems, such as Kali Linux, this results in the execution of /bin/sh -c <some command>. This is why you see "sh" errors even if you're using a ZSH shell. On Windows, it corresponds to running cmd.exe /C <some command>.

The output of the function depends on the underlying operating systems (as the system() command really just calls the OS API, for instance, the "CreateProcess" function which is part of the Windows API, or function such as, "fork()", "exec()" and other function for Unix-like systems). Therefore, the fact that it is on a different partition doesn't seem to matter much.

**Why the Error Happens:** It's not entirely clear why you're using the command "color", but you've given enough details to figure out what's wrong. In Windows, "color" is a built-in command in cmd.exe, and running it there won't cause any issues. However, in Unix-like systems (like Kali Linux), there is no "color" command, which means trying to run it will just lead to an error.

That said, it seems like you're not attempting to use a built-in command. Given the context, it makes sense that you're trying to execute a script named "color". If "color" is a script in your PATH but doesn't have execute permissions, trying to run it would result in the error "sh: 1: color: Permission denied". If it wasn’t in your PATH at all, you'd probably see "sh: 1: color: not found" instead.

You also mentioned that your script continued to work despite the error. This happens because if a command outputs to stderr or stdout, that output will appear in the Terminal, but no exception will be raised. In fact only the return value of the function "os.system" will change to reflect the error (e.g., 32512 for "sh: 1: color: Permission denied").

If you have some file named "color" that you're trying to execute, then make sure to supply it with execute permissions (note that your "main.py" file doesn’t need to be executable since you’re running it directly with the "python3" command; you don't need to use "./main.py" to execute it.). 

**Further notes:**
If you run a Python script in the following way: "python3 <file>", then it's okay if the file doesn't have an execute permission. By giving the script (in your case, "main.py") the execute permission and adding the line "#!/bin/python" at the top, it is possible to run the script in the following way: "./<file>" (if you're in the same directory of the script, otherwise, add it to the PATH or specify the relative/absolute path to it).

**Comment by hugovk** [comment] 2024-04-21 04:14
Thanks @L01i74 for the explanations, closing as not a termcolor issue.

**Closed by hugovk** 2024-04-21 04:14 UTC

**Comment by Ax1rc** [comment] 2024-05-31 02:30
Thank you for letting me know!
