### ISSUE TITLE
No longer works for output in Jupyter

### ISSUE THREAD

**Issue by mcrutch** [termcolor/termcolor#28] opened 2022-11-07 17:19 UTC
- Version 2.0.1 worked with Jupyter/JupyterLab
- Version 2.1.0 does not.

Pretty sure the _can_do_color function is the culprit.  While it might not have been intentional that it worked in Jupyter, it did.

https://github.com/termcolor/termcolor/blob/ec269e608a08b33beb739b6ab5f17b9217a5692a/src/termcolor/termcolor.py#L106

**Comment by hugovk** [comment] 2022-11-07 17:48
Please can you give more info?

A minimal reproducible example would help:

https://stackoverflow.com/help/minimal-reproducible-example

What did you do?

What did you expect?

What actually happened?

**Comment by mcrutch** [comment] 2022-11-07 17:57
- Run Jupyter Notebook or Jupyter Lab 
- Create a new notebook
- Execute this cell
```python
!pip install termcolor==2.0.1
from termcolor import colored
print(colored("Hello World","red"))
```
Result: Prints Hello World in red in the output cell
![image](https://user-images.githubusercontent.com/51446717/200381009-8cf2b678-9e9b-4bb8-83cd-baba9479a3d5.png)


- Restart kernel
- update cell and execute
```python
!pip install termcolor==2.1.0
from termcolor import colored
print(colored("Hello World","red"))
```
Results: Prints Hello World in theme default color
![image](https://user-images.githubusercontent.com/51446717/200380820-27eb2e85-6c9b-45a4-a7c9-73a52ec5776c.png)

**Comment by hugovk** [comment] 2022-11-07 18:53
Thank you!

Please can you let me know the value of each of the conditions in `_can_do_colour`? 

```python
print("ANSI_COLORS_DISABLED" in os.environ)
print("NO_COLOR" in os.environ)
print("FORCE_COLOR" in os.environ)
print(hasattr(sys.stdout, "isatty"))
print(hasattr(sys.stdout, "isatty") and sys.stdout.isatty())
print(os.environ.get("TERM") != "dumb")
```

**Comment by mcrutch** [comment] 2022-11-07 19:13
```
False
False
False
True
False
True
```

Possibly of value, `sys.stdout` is a `ipykernel.iostream.OutStream`

**Comment by hugovk** [comment] 2022-11-08 09:59
Thanks, so the problem is Jupyter is returning `False` for `sys.isatty`, despite being interactive.

Looks like they were going to set it to return `True`, but instead decided to default it to `True` and make it configurable to avoid problems with things like pagers:

https://github.com/ipython/ipykernel/pull/683

I'll dig a bit more, the short term workaround is to set an env var `FORCE_COLOR=1`, or configure `ipykernel.iostream.OutStream` so `isatty=True`.

**Comment by hugovk** [comment] 2022-11-19 11:18
I asked over at https://github.com/ipython/ipykernel/issues/1024.

**Comment by Nyaaa** [comment] 2022-11-20 20:13
Just FYI, this also affects PyCharm console, symptoms and values are the same. 2.0.1 works fine.

**Comment by hugovk** [comment] 2022-11-20 21:13
@Nyaaa Thanks, please could you open a new issue? These will likely have different fixes.

Here's the PyCharm bug report to upvote: https://youtrack.jetbrains.com/issue/PY-43798

Workaround:

```python
import os
os.environ["FORCE_COLOR"] = "1"
from termcolor import colored
print(colored("Hello World", "red"))
```

<img width="400" alt="image" src="https://user-images.githubusercontent.com/1324225/202926371-c15f965f-4353-42d1-9a5f-90a008cb34d0.png">

**Comment by hugovk** [comment] 2022-11-21 21:02
@mcrutch Please can you retest with IPython Kernel for Jupyter v6.18.0? This should now be fixed.

* https://github.com/ipython/ipykernel/issues/1024
* https://github.com/ipython/ipykernel/pull/1025

**Comment by realtimeprojects** [comment] 2022-11-23 13:29
A simple example how to reproduce this problem with the `tee` command:

`python3 -m termcolor | tee test.log`

**Comment by hugovk** [comment] 2022-11-23 14:21
@realtimeprojects This issue is for Jupyter. If you're piping the output then we have no idea if the receiving program can accept the colour codes, that's why we're doing tty detection. If you want to force it, please use the env var:

```sh
FORCE_COLOR=1 python3 -m termcolor | tee test.log
```

**Comment by realtimeprojects** [comment] 2022-11-28 11:39
@hugovk:

I was just commenting on this issue because I think this is a generic problem and not specific to Jupyter. Sorry for that!

I think it is a bad idea to check the sys.stdout for "isatty()" since you don't know where your colorized message will go to.  It is not guaruanteed that it will be streamed to sys.stdout (or sys.stderr). This is very applicatio specific. 

I use termcolor for colorizing "python logging" messages, which go to sys.stderr and if I run my app and redirecting stdout to a file, the logging messages are not colorized as well.

This check also fails when used in azure devops pipelines.

Furthermore, I consider the "isatty" check as rather "expensive" when done for each single message and you have a lot of log messages to colorize.

**Comment by hugovk** [comment] 2022-12-16 10:41
Closing this issue as fixed in Jupyter: https://github.com/termcolor/termcolor/issues/28#issuecomment-1322636281

---

@realtimeprojects Thank you for the feedback.

Can you use the `FORCE_COLOR=1` env var? 

I'm considering adding a `no_color` parameter (https://github.com/termcolor/termcolor/issues/2#issuecomment-1287010438), would a `force_color` parameter help?

> This check also fails when used in azure devops pipelines.

Yes, I guess this is like GitHub Actions: https://github.com/actions/runner/issues/241

I recommend adding `FORCE_COLOR=1` as an env var to your workflow (or similar), this will help for other tools as well:

* https://cs.github.com/?scopeName=All+repos&scope=&q=path%3A.github%2Fworkflows%2F*.yml+FORCE_COLOR

**Closed by hugovk** 2022-12-16 10:41 UTC

**Comment by hugovk** [comment] 2023-01-15 16:20
Please see PR https://github.com/termcolor/termcolor/pull/38 to add parameters to override the environment variables.
